# Generated by Django 6.0.4 on 2026-04-30 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['channel', 'user_id', 'status'], name='notificatio_channel_0e7b93_idx'),
        ),
    ]
